"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Button } from "@/app/components/ui/button";
import { Checkbox } from "@/app/components/ui/checkbox";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableCaption } from "@/app/components/ui/table";
import { Input } from "@/app/components/ui/input";
import { Textarea } from "@/app/components/ui/textarea";
import { ResearchSelect } from "@/app/components/research-workflow/select";
import { researchRequest } from "@/lib/research-workflow-api";
import { recordText, type ResearchSnapshot } from "@/lib/research-workflow";
import { claimQueueRows, validateQueue, type QueueDependency, type ResearchQueue } from "@/lib/research-queue";

function errorText(error: unknown) { return error instanceof Error ? error.message : "Queue request failed. Your original input is retained."; }
function display(status: string) { return status.replaceAll("-", " "); }
export function ClaimQueueView({ snapshot, queue }: { snapshot: ResearchSnapshot; queue: ResearchQueue }) {
  const [claimPage, setClaimPage] = useState(0); const [jobPage, setJobPage] = useState(0);
  const claims = claimQueueRows(snapshot, queue); const campaigns = new Map(snapshot.records.campaigns.map(c => [c.id, recordText(c, "title")]));
  const active = queue.jobs.filter(j => j.status === "running").length;
  const jobs = [...queue.jobs].sort((a, b) => a.priority - b.priority || a.created_at.localeCompare(b.created_at) || a.id.localeCompare(b.id));
  const events = queue.events.slice(-50).reverse();
  function download() {
    const url = URL.createObjectURL(new Blob([JSON.stringify(queue, null, 2)], { type: "application/json" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `private-research-queue-${queue.study_id}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <div className="space-y-5" data-testid="claim-queue">
    <p className="text-sm">Claims track scientific conclusions; campaigns execute checks. One job may supply evidence for several claims. Completion never automatically changes an assessment.</p>
    <p className="text-sm text-muted-foreground">{active} active jobs in this study / {queue.limits.study_jobs} study slots · global limit {queue.limits.global_jobs} · {queue.coverage.jobs} jobs · {queue.coverage.events} preserved events. No automatic experiment retries. Parallel execution does not establish independent evidence or review.</p>
    {!queue.workers_enabled ? <p className="text-sm text-amber-700 dark:text-amber-300">Scheduled workers are disabled in this environment. Jobs can be planned and preserved; automatic execution awaits worker activation.</p> : null}
    <Button size="sm" variant="outline" onClick={download}>Download private queue history</Button>
    <div className="overflow-x-auto"><Table className="w-full text-left text-sm"><TableCaption className="mb-2 text-left font-medium">Claim progress ({claims.length} claims; showing up to 50 per page)</TableCaption><TableHeader><TableRow className="border-b"><TableHead className="p-2">Claim</TableHead><TableHead className="p-2">Scientific assessment</TableHead><TableHead className="p-2">Queued work</TableHead></TableRow></TableHeader><TableBody>{claims.slice(claimPage * 50, (claimPage + 1) * 50).map(({ claim, assessment, campaignIds, jobs }) => <TableRow key={claim.id} className="border-b align-top"><TableCell className="max-w-lg whitespace-normal p-2">{recordText(claim, "description")}<p className="text-xs text-muted-foreground">{recordText(claim, "location")} · {recordText(claim, "claim_type")}</p></TableCell><TableCell className="p-2 capitalize">{assessment ? recordText(assessment, "label") : "Untested"}</TableCell><TableCell className="p-2">{jobs.length ? <ul className="space-y-1">{jobs.map(job => <li key={job.id}>{campaigns.get(job.campaign_id) ?? job.campaign_id}: {display(job.readiness)}</li>)}</ul> : campaignIds.length ? "Campaign linked; no queued job" : "No applicable campaign linked"}</TableCell></TableRow>)}</TableBody></Table></div>
    {!claims.length ? <p className="text-sm">No claims recorded. Add sourced claims and applicable checks before queueing a campaign.</p> : null}
    {claims.length > 50 ? <div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={claimPage === 0} onClick={() => setClaimPage(p => p - 1)}>Previous claims</Button><span className="text-xs">Page {claimPage + 1} / {Math.ceil(claims.length / 50)}</span><Button size="sm" variant="outline" disabled={(claimPage + 1) * 50 >= claims.length} onClick={() => setClaimPage(p => p + 1)}>Next claims</Button></div> : null}
    <div className="space-y-3"><h3 className="font-medium">Campaign jobs</h3>{jobs.length === 0 ? <p className="text-sm text-muted-foreground">No jobs queued. Existing scientific assessments remain available above.</p> : jobs.slice(jobPage * 20, (jobPage + 1) * 20).map(job => <article key={job.id} className="space-y-2 rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{campaigns.get(job.campaign_id) ?? job.campaign_id}</h4><span className="capitalize">{display(job.readiness)} · priority {job.priority}</span></div><p>{job.reason}</p>{job.blockers.length ? <ul className="list-disc space-y-1 pl-5 text-amber-700 dark:text-amber-300">{job.blockers.map(reason => <li key={reason}>{reason}</li>)}</ul> : null}<p className="break-all text-xs text-muted-foreground">Job {job.id} · {job.execution_mode} · last recorded change {job.updated_at}</p>{job.run_id ? <p className="break-all text-xs">Recorded run {job.run_id}: {job.run_status ?? "status unavailable"}. Scientific discrepancies are findings; review remains separate.</p> : null}{job.exclusive_resources.length ? <p className="text-xs">Exclusive resources: {job.exclusive_resources.join(", ")}</p> : null}{job.dependencies.length ? <ul className="space-y-1 text-xs">{job.dependencies.map(dep => <li className="break-all" key={dep.job_id}>Requires {display(dep.requirement)} from {dep.job_id}</li>)}</ul> : null}{job.followup_of ? <p className="break-all text-xs">Follow-up of {job.followup_of}</p> : null}</article>)}</div>
    {jobs.length > 20 ? <div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={jobPage === 0} onClick={() => setJobPage(p => p - 1)}>Previous jobs</Button><span className="text-xs">Page {jobPage + 1} / {Math.ceil(jobs.length / 20)}</span><Button size="sm" variant="outline" disabled={(jobPage + 1) * 20 >= jobs.length} onClick={() => setJobPage(p => p + 1)}>Next jobs</Button></div> : null}
    <details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Recorded event history ({queue.events.length}; latest 50 shown)</summary><ol className="mt-3 space-y-3 text-xs">{events.map(event => <li key={event.id} className="space-y-1 border-b pb-2"><p>{event.created_at} · {event.event} · {display(event.status)}</p><p className="break-all">Job {event.job_id}: {event.reason}</p><pre className="overflow-x-auto whitespace-pre-wrap break-all text-muted-foreground">{JSON.stringify(event.details, null, 2)}</pre></li>)}</ol></details>
    <p className="text-xs text-muted-foreground">{queue.limitations}</p>
  </div>;
}

function QueueEditor({ snapshot, queue, onSaved }: { snapshot: ResearchSnapshot; queue: ResearchQueue; onSaved: () => Promise<void> }) {
  const [campaign, setCampaign] = useState(""); const [mode, setMode] = useState("automatic"); const [raw, setRaw] = useState("");
  const [priority, setPriority] = useState("3"); const [resources, setResources] = useState(""); const [rationale, setRationale] = useState(""); const [previous, setPrevious] = useState("");
  const [dependencies, setDependencies] = useState<QueueDependency[]>([]); const [predecessor, setPredecessor] = useState(""); const [requirement, setRequirement] = useState("reviewed-evidence");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const request = useRef("");
  const applicable = new Set(snapshot.records.claim_checks.filter(c => c.applicability === "applicable").map(c => c.campaign_id));
  const campaigns = snapshot.records.campaigns.filter(c => applicable.has(c.id));
  function changed() { request.current = ""; }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); if (!request.current) request.current = crypto.randomUUID();
    try {
      await researchRequest(`/studies/${snapshot.study.id}/queue`, { method: "POST", body: JSON.stringify({ request_id: request.current, campaign_id: campaign, execution_mode: mode, priority: Number(priority), dependencies, exclusive_resources: resources.split("\n").map(r => r.trim()).filter(Boolean), rationale, followup_of: previous || null, raw_input: mode === "automatic" ? raw : null }) });
      await onSaved(); request.current = ""; setMessage(queue.workers_enabled ? "Job preserved. Ready automatic jobs are picked up by the scheduled bounded workers; manual tasks need a domain operator." : "Job preserved. Scheduled workers are disabled in this environment; execution is pending activation or a domain operator.");
    } catch (error) { setMessage(errorText(error)); } finally { setBusy(false); }
  }
  return <form onSubmit={submit} className="space-y-4 text-sm"><p>Queue a frozen campaign after linking its applicable claims. Existing-job prerequisites form an acyclic dependency graph. Priorities run from 1 (highest) to 5; slots and exclusive resources can delay otherwise ready jobs.</p>
    <label className="block space-y-1"><span className="font-medium">Campaign to queue</span><ResearchSelect label="Campaign to queue" required value={campaign} onChange={v => { setCampaign(v); changed(); }} options={[{ value: "", label: "Select a linked campaign" }, ...campaigns.map(c => ({ value: c.id, label: recordText(c, "title") }))]} /></label>
    <label className="block space-y-1"><span className="font-medium">Execution method</span><ResearchSelect label="Execution method" value={mode} onChange={v => { setMode(v); changed(); }} options={[{ value: "automatic", label: "Registered numerical adapter" }, { value: "manual", label: "Domain operator or source review" }]} /></label>
    {mode === "automatic" ? <><p className="text-xs text-muted-foreground">Exact input bytes must match the frozen protocol. Maximum 256 KB, 1,000 observations and 10 seconds of numerical computation. Other methods use a manual task.</p><label className="block space-y-1"><span className="font-medium">Original UTF-8 queue input file</span><Input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 256000) throw new Error("Queue input exceeds 256 KB."); const value = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(await file.arrayBuffer()); setRaw(value); changed(); } catch (error) { setMessage(errorText(error)); } }} /></label><label className="block space-y-1"><span className="font-medium">Original queue input text</span><Textarea required className="min-h-40 font-mono text-xs" value={raw} onChange={e => { setRaw(e.target.value); changed(); }} /></label></> : <p className="text-xs text-muted-foreground">Manual tasks record dependencies and work still required. Attach a run preserved by the domain importer when it is available; the scheduler does not execute arbitrary code, proofs or empirical measurements.</p>}
    <div className="grid gap-4 md:grid-cols-2"><label className="block space-y-1"><span className="font-medium">Queue priority</span><ResearchSelect label="Queue priority" value={priority} onChange={v => { setPriority(v); changed(); }} options={[1, 2, 3, 4, 5].map(v => ({ value: String(v), label: String(v) }))} /></label><label className="block space-y-1"><span className="font-medium">Follow-up of an earlier job</span><ResearchSelect label="Follow-up of an earlier job" value={previous} onChange={v => { setPrevious(v); changed(); }} options={[{ value: "", label: "Initial job" }, ...queue.jobs.map(j => ({ value: j.id, label: `${j.id.slice(0, 8)} · ${j.status}` }))]} /></label></div>
    <fieldset className="space-y-3 rounded-lg border p-3"><legend className="px-1 font-medium">Prerequisites</legend><ResearchSelect label="Predecessor job" value={predecessor} onChange={setPredecessor} options={[{ value: "", label: "Select an existing job" }, ...queue.jobs.filter(j => !dependencies.some(d => d.job_id === j.id)).map(j => ({ value: j.id, label: `${j.id.slice(0, 8)} · ${j.status}` }))]} /><ResearchSelect label="Dependency criterion" value={requirement} onChange={setRequirement} options={[{ value: "reviewed-evidence", label: "Claim evidence reviewed" }, { value: "complete-run", label: "Complete run recorded" }]} /><Button type="button" size="sm" variant="outline" disabled={!predecessor || dependencies.length >= 32} onClick={() => { setDependencies(d => [...d, { job_id: predecessor, requirement: requirement as QueueDependency["requirement"] }]); setPredecessor(""); changed(); }}>Add prerequisite</Button><ul className="space-y-2">{dependencies.map(dep => <li key={dep.job_id} className="flex flex-wrap items-center gap-2"><span className="break-all text-xs">{dep.job_id} · {display(dep.requirement)}</span><Button type="button" size="sm" variant="ghost" aria-label={`Remove prerequisite ${dep.job_id}`} onClick={() => { setDependencies(ds => ds.filter(d => d.job_id !== dep.job_id)); changed(); }}>Remove</Button></li>)}</ul></fieldset>
    <label className="block space-y-1"><span className="font-medium">Exclusive resources (one stable identity per line)</span><Textarea value={resources} placeholder="dataset:shared-preprocessing\nmachine:measurement-host" onChange={e => { setResources(e.target.value); changed(); }} /><span className="text-xs text-muted-foreground">Use shared lowercase names for resources that must not overlap across jobs or studies. Undeclared interference cannot be prevented by the scheduler.</span></label>
    <label className="block space-y-1"><span className="font-medium">Job rationale and follow-up reason</span><Textarea required maxLength={5000} value={rationale} onChange={e => { setRationale(e.target.value); changed(); }} /></label>{message ? <p role="status">{message}</p> : null}<Button disabled={busy || !campaign} type="submit">{busy ? "Preserving queue job…" : "Queue campaign"}</Button>
  </form>;
}

function QueueAction({ snapshot, queue, onSaved }: { snapshot: ResearchSnapshot; queue: ResearchQueue; onSaved: () => Promise<void> }) {
  const [jobId, setJobId] = useState(""); const [action, setAction] = useState("review"); const [reason, setReason] = useState(""); const [ids, setIds] = useState<string[]>([]); const [run, setRun] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const request = useRef("");
  const job = queue.jobs.find(j => j.id === jobId);
  const assessments = snapshot.records.assessments.filter(a => a.campaign_id === job?.campaign_id && Array.isArray(a.evidence) && a.evidence.some(e => e && typeof e === "object" && e.kind === "runs" && e.id === job?.run_id));
  function changed() { request.current = ""; }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); if (!request.current) request.current = crypto.randomUUID();
    try { await researchRequest(`/studies/${snapshot.study.id}/queue-actions`, { method: "POST", body: JSON.stringify({ request_id: request.current, job_id: jobId, action, reason, assessment_ids: action === "review" ? ids : [], run_id: action === "attach-run" ? run : null }) }); await onSaved(); request.current = ""; setMessage("Queue action and its original reason preserved."); }
    catch (error) { setMessage(errorText(error)); } finally { setBusy(false); }
  }
  return <form className="space-y-4 text-sm" onSubmit={submit}><p>Review needs an assessment for every applicable linked claim, citing this job’s run as an evidence object with kind “runs” and its full ID. Each assessment records its actual reviewer and independence. This action releases review prerequisites; it does not assert that the claims were reproduced.</p><ResearchSelect label="Queue action" value={action} onChange={v => { setAction(v); setJobId(""); setIds([]); setRun(""); changed(); }} options={[{ value: "review", label: "Accept recorded claim assessments" }, { value: "cancel", label: "Cancel an unstarted job" }, { value: "attach-run", label: "Attach an external domain run" }]} /><ResearchSelect label="Job for queue action" required value={jobId} onChange={v => { setJobId(v); setIds([]); setRun(""); changed(); }} options={[{ value: "", label: "Select a job" }, ...queue.jobs.filter(j => action === "review" ? j.status === "awaiting-review" : action === "cancel" ? ["queued", "manual"].includes(j.status) : j.status === "manual").map(j => ({ value: j.id, label: `${j.id.slice(0, 8)} · ${j.status}` }))]} />
    {action === "review" ? <fieldset className="space-y-2"><legend className="mb-2 font-medium">Preserved claim assessments</legend>{assessments.length ? assessments.map(a => <label key={a.id} className="flex items-start gap-2"><Checkbox checked={ids.includes(a.id)} onCheckedChange={checked => { setIds(prior => checked ? [...prior, a.id] : prior.filter(id => id !== a.id)); changed(); }} /><span className="break-all">{recordText(a, "label")} · {String(a.claim_id)} · {a.id}</span></label>) : <p className="text-xs text-muted-foreground">Add claim-specific assessments citing this job’s recorded run before accepting review.</p>}</fieldset> : null}
    {action === "attach-run" ? <ResearchSelect label="Preserved external run" required value={run} onChange={v => { setRun(v); changed(); }} options={[{ value: "", label: "Select a domain run in this campaign" }, ...snapshot.records.runs.filter(r => r.campaign_id === job?.campaign_id).map(r => ({ value: r.id, label: `${r.id} · ${recordText(r, "status")}` }))]} /> : null}
    <label className="block space-y-1"><span className="font-medium">Recorded action reason</span><Textarea required maxLength={5000} value={reason} onChange={e => { setReason(e.target.value); changed(); }} /></label>{message ? <p role="status">{message}</p> : null}<Button type="submit" disabled={busy || !jobId || (action === "review" && ids.length === 0) || (action === "attach-run" && !run)}>{busy ? "Recording queue action…" : "Preserve queue action"}</Button>
  </form>;
}

export function ClaimQueue({ snapshot, onEvidenceChanged }: { snapshot: ResearchSnapshot; onEvidenceChanged: () => Promise<void> }) {
  const [queue, setQueue] = useState<ResearchQueue | null>(null); const [error, setError] = useState(""); const [revision, setRevision] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; let active = true;
    async function load() {
      try { const result = validateQueue(await researchRequest(`/studies/${snapshot.study.id}/queue`, { signal: controller.signal }), snapshot.study.id); if (active) { setQueue(result); setError(""); } }
      catch (failure) { if (active) setError(errorText(failure)); }
      finally { if (active) timer = setTimeout(load, 10000); }
    }
    void load(); return () => { active = false; controller.abort(); clearTimeout(timer); };
  }, [snapshot.study.id, revision]);
  async function saved() { setRevision(r => r + 1); await onEvidenceChanged(); }
  return <section className="space-y-4 rounded-lg border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Claim evaluation queue</h2><Button size="sm" variant="outline" onClick={() => void saved().catch(failure => setError(errorText(failure)))}>Refresh queue and evidence</Button></div>{error ? <p role="alert" className="text-sm text-destructive">{error} {queue ? "Previously retrieved queue shown; current status is unverified." : "Queue counts and status are unavailable."}</p> : null}{queue ? <><ClaimQueueView snapshot={snapshot} queue={queue} /><details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Queue a campaign with prerequisites</summary><div className="mt-4"><QueueEditor snapshot={snapshot} queue={queue} onSaved={saved} /></div></details><details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Review, cancel or attach recorded evidence</summary><div className="mt-4"><QueueAction snapshot={snapshot} queue={queue} onSaved={saved} /></div></details></> : !error ? <p role="status">Loading the private claim queue…</p> : null}</section>;
}
