import { Http2Header } from "@/app/components/http2-study/header";
import { getHttp2Data } from "@/lib/http2-study-server";
import { HTTP2_STUDY_MODULE_PATH as PATH } from "@/lib/test-modules";
export const dynamic = "force-dynamic";
export default async function Methods() {
  const data = await getHttp2Data();
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6"><Http2Header title="Methods, protocol and claim coverage" description="Versioned decisions, reproducible source hashes, failed pilots and limits of the evidence." />
    <section className="space-y-3 rounded-lg border p-4 text-sm"><h2 className="font-medium">Declared scope</h2><p>The main campaign is a census of 57 released JSON datasets and 7,176 designed case observations. Exact integer comparisons use the 15 Table 5 configurations; rounded percentages use ±0.05 percentage points. Cases and versions are correlated. No population confidence interval, significance test or random sampling claim is supported.</p><p>The original classifier is isolated from pristine, pinned author code. A separate classifier preserves absent and unrecognized worker evidence. Its broad E/G/R and ignore-to-drop scores do not replace RFC semantics. GOAWAY may legitimately escalate a stream error. Historical worker resources, exact configurations and execution UTC remain missing.</p><p>Figure 8 corrections and 72 fresh loopback observations have separate protocols. Neither replaces the original archived campaign. The loopback controls use a current endpoint and one workstation; full local/cloud proxy replication, exploits and operational security effectiveness remain untested. Simulator, orbital epoch and satellite maximum-resource checks are inapplicable.</p><p>Main paper: all 16 pages, Figures 1–8, Tables 1–9 and Appendices A–B reviewed. Figures 1–3 illustrate framing/taxonomy/architecture; Tables 1–4 and 6 describe framing and deployment selection; Tables 7–9 describe historical case mapping and the test suite. Figure 4 raster cells are not fully independently checked. Numerical Figure 7/8 coverage is limited to the recorded prose comparisons and underlying vectors.</p><a className="inline-block underline underline-offset-4" href={`${PATH}/api/results`}>Download protocols, analysis provenance, source inventory and measurements</a></section>
    {!data ? <p>Recorded methods are unavailable.</p> : <>
      <section className="space-y-3"><h2 className="text-lg font-medium">Claim-by-claim assessment</h2>{data.claims.map(c => <article key={c.claim_id} className="rounded-lg border p-4 text-sm"><p className="text-xs text-muted-foreground">{c.location} · <strong>{c.assessment}</strong></p><h3 className="mt-1 font-medium">{c.description}</h3><p className="mt-2">{c.evidence}</p><p className="mt-2 text-muted-foreground">{c.limitation}</p></article>)}</section>
      <section className="space-y-3"><h2 className="text-lg font-medium">Frozen protocols</h2>{data.protocols.map(p => <details key={p.id} className="rounded-lg border p-4 text-sm"><summary className="cursor-pointer">{p.id} · version {p.version} · {p.stage}</summary><p className="mt-2 break-all text-xs">SHA-256 {p.sha256} · frozen UTC {p.locked_at ?? "unavailable"}</p><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(p.document, null, 2)}</pre></details>)}</section>
      <section className="rounded-lg border p-4 text-sm"><h2 className="font-medium">Failed or excluded runs</h2>{data.runs.filter(r => r.status !== "complete").map(r => <p className="mt-2" key={r.id}>{r.id} · {r.status}: {r.reason}</p>)}<p className="mt-3 text-muted-foreground">Metadata / case 0 are excluded from the test census and retained in private raw artifacts. Unrecognized evidence is reported as unknown, without inferring a packet drop. Run status does not assert RFC compliance.</p></section>
      <section className="rounded-lg border p-4 text-sm"><h2 className="font-medium">Limits and costs</h2>{data.campaign.limitations.map(l => <p className="mt-2 text-muted-foreground" key={l}>{l}</p>)}<pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(data.campaign.costs, null, 2)}</pre><p className="mt-2 text-muted-foreground">Purchased experiment compute: $0 incremental; workstation allocation cost unavailable. Model-evaluation costs and release verification are recorded separately in the release report.</p></section>
    </>}
  </main>;
}
