"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/app/components/ui/button";
import { Table } from "@/app/components/ui/table";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/app/components/ui/card";
import { COUNTRY_LABELS, LEO_COUNTRIES, isPrimaryConfiguration, scenarioRows, type LeoData } from "@/lib/leo-study";
import { LEO_STUDY_MODULE_PATH } from "@/lib/test-modules";
const COLORS = ["var(--chart-1)", "var(--chart-2)", "var(--chart-3)", "var(--chart-4)", "var(--chart-5)"];
const number = (n: number, digits = 2) => n.toLocaleString("en-US", { maximumFractionDigits: digits });
type Series = { label: string; points: { x: number; y: number }[] };
function LineChart({ series, xLabel, title }: { series: Series[]; xLabel: string; title: string }) {
  const all = series.flatMap(s => s.points);
  if (!all.length) return <p className="text-sm text-muted-foreground">No matching recorded scenarios.</p>;
  const maxX = Math.max(1, ...all.map(p => p.x)), maxY = Math.max(1, ...all.map(p => p.y)) * 1.08;
  const x = (v: number) => 68 + 490 * v / maxX, y = (v: number) => 248 - 220 * v / maxY;
  return <div><svg viewBox="0 0 600 300" role="img" aria-label={title} className="w-full text-muted-foreground"><title>{title}</title>
    {[0, 0.25, 0.5, 0.75, 1].map(f => <g key={f}><line x1="68" x2="558" y1={y(maxY*f)} y2={y(maxY*f)} stroke="currentColor" opacity="0.15" /><text x="60" y={y(maxY*f)+4} textAnchor="end" fill="currentColor" fontSize="11">{number(maxY*f, 0)}</text><text x={x(maxX*f)} y="267" textAnchor="middle" fill="currentColor" fontSize="11">{number(maxX*f, 0)}</text></g>)}
    <text x="68" y="16" fill="currentColor" fontSize="11">Capacity (Gbps)</text><text x="313" y="290" textAnchor="middle" fill="currentColor" fontSize="11">{xLabel}</text>
    {series.map((s, i) => <g key={s.label}><polyline points={[...s.points].sort((a,b) => a.x-b.x).map(p => `${x(p.x)},${y(p.y)}`).join(" ")} fill="none" stroke={COLORS[i % COLORS.length]} strokeWidth="2" />{s.points.map(p => <circle key={p.x} cx={x(p.x)} cy={y(p.y)} r="3" fill={COLORS[i % COLORS.length]}><title>{`${s.label}: ${number(p.x)} ${xLabel}, ${number(p.y)} Gbps`}</title></circle>)}</g>)}
  </svg><div className="flex flex-wrap gap-x-4 gap-y-2 text-xs">{series.map((s,i) => <span key={s.label} className="flex items-center gap-1"><span className="h-2 w-4 rounded-sm" style={{ background: COLORS[i % COLORS.length] }} />{s.label}</span>)}</div></div>;
}
function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>;
}
export function LeoDashboard({ data }: { data: LeoData }) {
  const [country, setCountry] = useState<string>("tonga");
  const rows = scenarioRows(data, country);
  const saturationRows = data.saturation ? scenarioRows(data.saturation, country) : [];
  const saturationCurve = saturationRows.filter(r => r.variant === "paper" && r.second === 0);
  const baseline = rows.filter(r => r.constellation === "starlink_5shells" && r.beam_policy === "greedy-coordinated" && r.ku_gbps === 1.28 && r.variant === "paper" && r.second === 0);
  const placement = ["population", "gcb-0", "gcb-1000", "gcb-10000", "gcb-100000"].map(policy => ({ label: policy === "population" ? "Population" : policy === "gcb-0" ? "GCB, uncapped" : `GCB ≥ ${number(Number(policy.slice(4)), 0)} people/cell`, points: baseline.filter(r => r.placement === policy).map(r => ({ x: r.requested_terminals, y: r.capacity_gbps })) })).filter(s => s.points.length);
  const time = rows.filter(r => isPrimaryConfiguration(r) && r.second < 15);
  const distant = rows.filter(r => isPrimaryConfiguration(r) && r.second >= 15);
  const upgrades = rows.filter(r => r.second === 0 && r.requested_terminals === 200000 && r.placement === "gcb-0" && r.variant === "paper" && r.beam_policy === "greedy-coordinated" && r.constellation === "starlink_5shells").sort((a,b) => a.ku_gbps-b.ku_gbps);
  const beamRows = rows.filter(r => r.second === 0 && r.requested_terminals === 200000 && r.ku_gbps === 1.28 && r.constellation === "starlink_5shells").sort((a,b) => a.placement.localeCompare(b.placement) || a.variant.localeCompare(b.variant) || a.beam_policy.localeCompare(b.beam_policy));
  const growth = rows.filter(r => r.second === 0 && r.placement === "uniform").reduce<Series[]>((acc,r) => {
    let s = acc.find(v => v.label === `${number(r.satellites,0)} satellites`);
    if (!s) { s = { label: `${number(r.satellites,0)} satellites`, points: [] }; acc.push(s); }
    s.points.push({ x: r.requested_terminals, y: r.capacity_gbps }); return acc;
  }, []);
  const max = Math.max(1, ...data.summaries.flatMap(s => [s.published_gbps,s.max_gbps]));
  return <div className="space-y-6">
    <div className="rounded-lg border bg-muted/40 p-4 text-sm"><p className="font-medium">{data.campaign.recorded_samples}/{data.campaign.planned_samples} planned model states saved · {data.campaign.status}</p><p className="mt-1 text-muted-foreground">Idealized downlink capacity with no incumbent traffic. Each state is deterministic. Temporal ranges are not confidence intervals; cable capacity is a design or literature proxy, not observed traffic lost.</p></div>
    <Panel title="Published capacity versus the initial fixed-budget reproduction" description="Table 1 maximum compared with 200,000 requested terminals and 15 one-second Config A snapshots. Whiskers show time-state min/max. A fixed budget need not achieve the maximum.">
      <svg viewBox="0 0 720 340" role="img" aria-label="Six-country published and reproduced capacities" className="w-full text-muted-foreground"><title>Published Table 1 and reproduced mean capacity, in Gbps</title>
        {[0,.25,.5,.75,1].map(f => <g key={f}><line x1={130+540*f} x2={130+540*f} y1="15" y2="280" stroke="currentColor" opacity=".15"/><text x={130+540*f} y="303" fill="currentColor" textAnchor="middle" fontSize="11">{number(max*f,0)}</text></g>)}
        {LEO_COUNTRIES.map((c,i) => { const s=data.summaries.find(v=>v.country===c); if (!s) return <text key={c} x="8" y={36+i*44} fill="currentColor" fontSize="12">{COUNTRY_LABELS[c]}: unavailable</text>; return <g key={c}><text x="120" y={36+i*44} fill="currentColor" textAnchor="end" fontSize="12">{COUNTRY_LABELS[c]}</text><rect x="130" y={20+i*44} width={540*s.published_gbps/max} height="10" fill={COLORS[1]}><title>{`${COUNTRY_LABELS[c]} published: ${number(s.published_gbps)} Gbps`}</title></rect><rect x="130" y={33+i*44} width={540*s.mean_gbps/max} height="10" fill={COLORS[0]}><title>{`${COUNTRY_LABELS[c]} reproduction: ${number(s.mean_gbps)} Gbps; ${s.snapshots} snapshots`}</title></rect><path d={`M ${130+540*s.min_gbps/max} ${33+i*44} v 10 M ${130+540*s.min_gbps/max} ${38+i*44} H ${130+540*s.max_gbps/max} M ${130+540*s.max_gbps/max} ${33+i*44} v 10`} stroke="currentColor" fill="none" /></g>; })}
        <text x="400" y="326" fill="currentColor" textAnchor="middle" fontSize="11">Capacity (Gbps)</text>
      </svg>
      <div className="mb-3 flex gap-4 text-xs"><span className="flex items-center gap-1"><span className="h-2 w-4" style={{background:COLORS[0]}}/>Reproduction</span><span className="flex items-center gap-1"><span className="h-2 w-4" style={{background:COLORS[1]}}/>Published paper</span></div>
      <div className="overflow-x-auto"><Table className="w-full text-left text-sm"><thead><tr>{["Country","Paper (Gbps)","Reproduced (Gbps)","Difference","Capacity / cable proxy","Assessment"].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{data.summaries.map(s=><tr key={s.country} className="border-t"><td className="p-2">{COUNTRY_LABELS[s.country]}</td><td className="p-2 tabular-nums">{number(s.published_gbps)}</td><td className="p-2 tabular-nums">{number(s.mean_gbps)} [{number(s.min_gbps)}–{number(s.max_gbps)}]</td><td className="p-2 tabular-nums">{s.relative_difference_percent>0?"+":""}{number(s.relative_difference_percent)}%</td><td className="p-2 tabular-nums">{number(s.failover_percent)}%</td><td className="p-2">{s.assessment}</td></tr>)}</tbody></Table></div>
      <p className="mt-3 text-xs text-muted-foreground">The ±5% agreement threshold was declared before execution. It is a numerical comparison rule. Percentages above 100% compare idealized capacity with the cable proxy and do not guarantee national service.</p>
      <p className="mt-2 text-xs text-muted-foreground">Source inconsistency: Table 1 prints Lithuania’s capacity as 2,005 Gbps, cable proxy as 101 Gbps, and fraction as 198%. The printed capacities imply 1,985.15%. We retain the capacity values and compute fractions from them.</p>
    </Panel>
    {data.saturation ? <Panel title="Terminal-budget saturation follow-up" description="Exploratory follow-up recorded separately after the initial campaign. The 2-million-terminal temporal summary and four tested budgets investigate whether fixed budgets explain discrepancies.">
      <p className="mb-3 text-sm text-muted-foreground">{data.saturation.campaign.recorded_samples}/{data.saturation.campaign.planned_samples} saved states. A plateau is specific to this beam heuristic, allocation and epoch. More terminals can change heuristic choices, so these results do not prove an optimal RF capacity ceiling.</p>
      <Table className="text-left text-sm"><thead><tr>{["Country", "Paper (Gbps)", "2M terminals (Gbps)", "Difference", "Assessment"].map(v => <th className="p-2" key={v}>{v}</th>)}</tr></thead><tbody>{data.saturation.summaries.map(s => <tr key={s.country} className="border-t"><td className="p-2">{COUNTRY_LABELS[s.country]}</td><td className="p-2">{number(s.published_gbps)}</td><td className="p-2">{number(s.mean_gbps)} [{number(s.min_gbps)}–{number(s.max_gbps)}]</td><td className="p-2">{number(s.relative_difference_percent)}%</td><td className="p-2">{s.assessment}</td></tr>)}</tbody></Table>
    </Panel> : null}
    <div className="flex flex-wrap items-center gap-2" aria-label="Select country">{LEO_COUNTRIES.map(c=><Button key={c} variant={country===c?"default":"outline"} size="sm" aria-pressed={country===c} onClick={()=>setCountry(c)}>{COUNTRY_LABELS[c]}</Button>)}<Link href={`${LEO_STUDY_MODULE_PATH}/chat?country=${country}`} className="ml-auto text-sm underline underline-offset-4">Ask AI about {COUNTRY_LABELS[country]}</Link></div>
    <div className="grid gap-6 lg:grid-cols-2">
      {data.saturation ? <Panel title={`${COUNTRY_LABELS[country]} · budget convergence`} description="Config A, uncapped paper GCB, coordinated beams at t=0. Compare the separate high-budget experiment with the original 200,000-terminal point."><LineChart series={[{label:"Recorded budget sensitivity",points:[...baseline.filter(r=>r.placement==="gcb-0" && r.requested_terminals===200000),...saturationCurve].map(r=>({x:r.requested_terminals,y:r.capacity_gbps}))}]} xLabel="Requested terminals" title={`${COUNTRY_LABELS[country]} high-budget capacity convergence`} /></Panel> : null}
      <Panel title={`${COUNTRY_LABELS[country]} · terminal placement`} description="Matched Config A, coordinated beams, paper allocation semantics, and the same orbital epoch. Caps are minimum population per eligible cell."><LineChart series={placement} xLabel="Requested terminals" title={`${COUNTRY_LABELS[country]} placement capacity curves`} /></Panel>
      <Panel title="Orbital state sensitivity" description="Beams remapped at each state. Fifteen adjacent seconds describe local variability; they are not independent experiments."><LineChart series={[{ label:"Primary configuration", points:time.map(r=>({x:r.second,y:r.capacity_gbps})) }]} xLabel="Seconds from artifact epoch" title={`${COUNTRY_LABELS[country]} orbital capacity over 15 seconds`} /><p className="mt-3 text-xs text-muted-foreground">Distant snapshots: {distant.length ? distant.map(r=>`${r.second/3600}h: ${number(r.capacity_gbps)} Gbps`).join(" · ") : "unavailable"}. Three later states do not establish long-term availability.</p></Panel>
      <Panel title="Constellation growth" description="Uniform deployment in the released 14,316 and 34,224 satellite configurations. These optimistic model inputs are separate from the baseline placement curves."><LineChart series={growth} xLabel="Requested terminals" title={`${COUNTRY_LABELS[country]} constellation growth`} /></Panel>
      <Panel title="Link-rate sensitivity" description="Baseline constellation and uncapped GCB. The 2.5-Gbps case also doubles ISL rates in the released code; Ka rates remain unchanged. This is a partial Config C sensitivity."><div className="space-y-4">{upgrades.map(r=><div key={r.id} className="text-sm"><div className="mb-1 flex justify-between gap-2"><span>{r.ku_gbps} Gbps per Ku beam</span><span className="tabular-nums">{number(r.capacity_gbps)} Gbps</span></div><div className="h-3 rounded bg-muted"><div className="h-3 rounded bg-primary" style={{width:`${100*r.capacity_gbps/Math.max(1,...upgrades.map(v=>v.capacity_gbps))}%`}} /></div></div>)}</div></Panel>
    </div>
    <Panel title="Beam policy and allocation semantics" description="The full matched 200,000-requested-terminal ablation at t=0. Artifact caps can leave terminals undeployed, which changes the effective treatment."><div className="overflow-x-auto"><Table className="w-full text-left text-sm"><thead><tr>{["Placement","Allocation variant","Beam policy","Deployed","Capacity (Gbps)","Cells served"].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{beamRows.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.placement}</td><td className="p-2">{r.variant}</td><td className="p-2">{r.beam_policy.replace("greedy-","")}</td><td className="p-2 tabular-nums">{number(r.deployed_terminals,0)}</td><td className="p-2 tabular-nums">{number(r.capacity_gbps)}</td><td className="p-2 tabular-nums">{r.served_cells}/{r.cells}</td></tr>)}</tbody></Table></div></Panel>
    <details className="rounded-lg border p-5"><summary className="cursor-pointer text-sm font-medium">Recorded scenarios for {COUNTRY_LABELS[country]} ({rows.length})</summary><a href={`${LEO_STUDY_MODULE_PATH}/api/results`} className="my-3 inline-block text-sm underline underline-offset-4">Download all recorded results (JSON)</a><div className="max-h-96 overflow-auto"><Table className="w-full text-left text-xs"><thead><tr>{["Satellites","Requested","Placement","Beam","Ku","Variant","Second","Gbps","Validation"].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.satellites}</td><td className="p-2">{r.requested_terminals}</td><td className="p-2">{r.placement}</td><td className="p-2">{r.beam_policy}</td><td className="p-2">{r.ku_gbps}</td><td className="p-2">{r.variant}</td><td className="p-2">{r.second}</td><td className="p-2">{number(r.capacity_gbps)}</td><td className="p-2">{r.validation_errors.length?r.validation_errors.join("; "):"passed"}</td></tr>)}</tbody></Table></div></details>
  </div>;
}
