import assert from 'node:assert/strict';
import test from 'node:test';
import {prepareAndQueue,validatePreparation} from '../lib/research-preparation.ts';
function plan(){return {id:'p',plan_id:'version-1',manifest_sha256:'a'.repeat(64),planned_jobs:3,queued_jobs:0,automatic_jobs:2,manual_jobs:1,status:'prepared',provenance:{},jobs:['a','b','c'].map((id,i)=>({id,campaign_id:'campaign-'+id,title:id,execution_mode:i===2?'manual':'automatic',status:'not-queued'}))};}
const status=p=>({version:'research-preparation-v1',available_plan:null,uploaded_plan_bytes:250000,limitation:'Development fixture',prepared:[p]});
test('preparation chains every bounded job and confirms its persisted identity',async()=>{const p=plan(),calls=[],messages=[];await prepareAndQueue('s','r',m=>messages.push(m),async(path,options)=>{const b=JSON.parse(options.body);calls.push(b);if(b.action==='prepare')return {prepared:p};const j=p.jobs.find(j=>j.id===b.job_id);return {job:{...j,study_id:'s',status:j.execution_mode==='manual'?'manual':'queued'}};},'{\n "exact": true\n}');assert.deepEqual(calls.map(b=>b.action),['prepare','enqueue','enqueue','enqueue']);assert.equal(calls[0].plan_input,'{\n "exact": true\n}');assert.equal(p.queued_jobs,3);assert.match(messages.at(-1),/Scientific review remains separate/);});
test('a failed queue request stops further jobs and resume skips all retained states',async()=>{const p=plan(),attempts=[];await assert.rejects(prepareAndQueue('s','r',()=>{},async(path,options)=>{const b=JSON.parse(options.body);if(b.action==='prepare')return {prepared:p};attempts.push(b.job_id);if(b.job_id==='b')throw new Error('Interrupted');return {job:{...p.jobs[0],study_id:'s',status:'queued'}};}),/Interrupted/);assert.deepEqual(attempts,['a','b']);p.jobs[0].status='failed';p.queued_jobs=1;const resumed=[];await prepareAndQueue('s','r',()=>{},async(path,options)=>{if(!options)return status(p);const b=JSON.parse(options.body);resumed.push(b);const j=p.jobs.find(j=>j.id===b.job_id);return {job:{...j,study_id:'s',status:j.execution_mode==='manual'?'manual':'queued'}};},undefined,'p');assert.deepEqual(resumed.map(b=>b.job_id),['b','c']);assert.ok(resumed.every(b=>b.action==='enqueue'&&!('raw_input' in b)));});
test('missing or ambiguous coverage never becomes a successful queue',async()=>{for(const change of [p=>p.queued_jobs=1,p=>p.jobs[1].id=p.jobs[0].id,p=>p.jobs[0].status='unknown',p=>p.automatic_jobs=0,p=>p.jobs=[]]){const p=plan();change(p);assert.throws(()=>validatePreparation(status(p)),/coverage/);}await assert.rejects(prepareAndQueue('s','r',()=>{},async()=>({prepared:plan()}),undefined,'absent'),/incomplete/);});
test('HTTP success with wrong study/job or no job stops and reports unconfirmed state',async()=>{for(const response of [{},{job:{...plan().jobs[0],study_id:'wrong',status:'queued'}},{job:{...plan().jobs[0],id:'wrong',study_id:'s',status:'queued'}}]){let calls=0;await assert.rejects(prepareAndQueue('s','r',()=>{},async()=>++calls===1?{prepared:plan()}:response),/does not confirm/);assert.equal(calls,2);}});
