import assert from 'node:assert/strict';
import test from 'node:test';
import {RECORD_KINDS,claimCounts,latestByClaim,measurementsCsv,preparationSteps,researchApiBase,safeSourceUrl,validateSnapshot,valueLabel} from '../lib/research-workflow.ts';
import {getTestModuleForPath,RESEARCH_WORKFLOW_MODULE_PATH as PATH} from '../lib/test-modules.ts';
function snapshot(){const records=Object.fromEntries(RECORD_KINDS.map(k=>[k,[]]));return {study:{id:'study'},access:'published-snapshot',records,coverage:Object.fromEntries(RECORD_KINDS.map(k=>[k,0]))};}
test('API target rejects embedded credentials and non-loopback cleartext',()=>{assert.equal(researchApiBase(undefined),undefined);assert.equal(researchApiBase('http://127.0.0.1:4102/'),'http://127.0.0.1:4102');for(const value of ['http://example.org','https://user:secret@example.org','https://example.org?token=secret'])assert.throws(()=>researchApiBase(value));});
test('assessment times compare actual instants across timezone offsets',()=>{const rows=[{id:'old',claim_id:'c',created_at:'2026-10-07T12:00:00+03:00'},{id:'new',claim_id:'c',created_at:'2026-10-07T10:00:00Z'}];assert.equal(latestByClaim(rows).get('c').id,'new');assert.throws(()=>latestByClaim([{id:'bad',claim_id:'c',created_at:'unknown'}]));});
test('zero, missing, invalid and tiny scientific values stay distinct',()=>{assert.equal(valueLabel(0),'0');assert.equal(valueLabel(null),'missing');assert.equal(valueLabel(''),'invalid');assert.equal(valueLabel('NaN'),'invalid');assert.equal(valueLabel(false),'invalid');assert.equal(valueLabel('0.00001'),'0.00001');});
test('current assessment is selected by identity and recorded version time, not array order',()=>{const s=snapshot();s.records.claims=[{id:'c',study_id:'study',created_at:'2026-10-07'}];s.records.assessments=[{id:'new',study_id:'study',claim_id:'c',created_at:'2026-10-07',label:'discrepant'},{id:'old',study_id:'study',claim_id:'c',created_at:'2026-10-06',label:'untested'}];assert.equal(latestByClaim(s.records.assessments).get('c').id,'new');assert.equal(claimCounts(s).discrepant,1);assert.equal(s.records.assessments.length,2);});
test('absent assessment is untested; invalid or truncated coverage is not silently normalized',()=>{const s=snapshot();s.records.claims=[{id:'c',study_id:'study',created_at:'2026-10-07'}];assert.equal(claimCounts(s).untested,1);assert.throws(()=>validateSnapshot(s));s.coverage.claims=1;assert.equal(validateSnapshot(s),s);s.records.claims[0].study_id='another-study';assert.throws(()=>validateSnapshot(s));});
test('CSV preserves missing values and recorded negatives while neutralizing source text formulas',()=>{const s=snapshot();s.records.measurements=[{observation_id:'=HYPERLINK("bad")',configuration_identity:'fixed',metric:'latency',units:'ms',value:null,status:'missing',reason:'absent'},{observation_id:'a',configuration_identity:'fixed',metric:'latency',units:'ms',value:-2,status:'recorded',reason:null}];const csv=measurementsCsv(s);assert.ok(csv.includes("'="));assert.ok(csv.includes('"missing",,"absent"'));assert.ok(csv.includes('"recorded","-2",'));});
test('public source links cannot execute embedded instructions',()=>{assert.equal(safeSourceUrl('javascript:alert(1)'),null);assert.equal(safeSourceUrl('file:///private/artifact'),null);assert.equal(safeSourceUrl('https://example.org/paper'),'https://example.org/paper');});
test('workflow pages and exports belong to the shared module',()=>{for(const suffix of ['/new-study','/workspace','/workspace/abc?view=gaps','/studies/abc','/api/studies/abc/export'])assert.equal(getTestModuleForPath(PATH+suffix)?.id,'research-verification');});
test('metadata-only intake has missing preparation rather than implied claim coverage or execution',()=>{const s=snapshot();assert.deepEqual(preparationSteps(s).map(step=>step.count),[0,0,0,0,0,0]);assert.equal(preparationSteps(s).find(step=>step.count===0).id,'sources');assert.deepEqual(claimCounts(s),{reproduced:0,discrepant:0,inconclusive:0,untested:0});});
test('unlinked, inapplicable and orphaned campaigns do not satisfy queue preparation',()=>{const s=snapshot();s.records.protocols=[{id:'p'}];s.records.campaigns=[{id:'valid',protocol_id:'p'},{id:'orphan',protocol_id:'absent'}];s.records.claim_checks=[{campaign_id:'valid',applicability:'inapplicable'},{campaign_id:'orphan',applicability:'applicable'}];assert.equal(preparationSteps(s).find(step=>step.id==='campaigns').count,1);assert.equal(preparationSteps(s).find(step=>step.id==='claim_checks').count,0);s.records.claim_checks.push({campaign_id:'valid',applicability:'applicable'},{campaign_id:'valid',applicability:'applicable'});assert.equal(preparationSteps(s).find(step=>step.id==='claim_checks').count,1);assert.equal(s.records.runs.length,0);});
