import type { ResearchSnapshot, RecordKind, ResearchRecord } from "@/lib/research-workflow";
import type { ResearchQueue, QueueJob } from "@/lib/research-queue";

// Public teaching fixtures. IDs/times identify examples, never real executions.
const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const study = id(1), time = "2026-10-07T00:00:00Z";
const kinds: RecordKind[] = ["sources", "claims", "protocols", "configurations", "campaigns", "claim_checks", "runs", "published_values", "measurements", "summaries", "assessments", "gaps", "reviews", "publications"];
const records: Record<RecordKind, ResearchRecord[]> = { sources: [], claims: [], protocols: [], configurations: [], campaigns: [], claim_checks: [], runs: [], published_values: [], measurements: [], summaries: [], assessments: [], gaps: [], reviews: [], publications: [] };
const descriptions = ["Example: compare reported latency cells", "Example: compare another latency cell in the same campaign", "Example: validate a causal explanation", "Example: interpret a normative standard", "Example: review recorded discrepant evidence", "Example: investigate an expired attempt"];
records.claims = descriptions.map((description, n) => ({ id: id(10 + n), study_id: study, created_at: time, description, location: "Illustration; no paper source", claim_type: n === 2 ? "causal" : n === 3 ? "standard" : "numerical" }));
records.campaigns = ["Shared numerical campaign", "Causal intervention requiring equipment", "Substantive standards review", "Numerical evidence awaiting review", "Expired worker attempt"].map((title, n) => ({ id: id(30 + n), study_id: study, created_at: time, title }));
records.claim_checks = [0, 0, 1, 2, 3, 4].map((n, index) => ({ id: id(50 + index), study_id: study, created_at: time, claim_id: id(10 + index), campaign_id: id(30 + n), applicability: "applicable" }));
export const QUEUE_EXAMPLE_SNAPSHOT: ResearchSnapshot = { study: { id: study, title: "Illustrative queue", paper_url: "https://example.org/illustration", domain: "Workflow example", scope: "Synthetic teaching fixture; no paper verification or scientific findings.", origin_module: null, created_at: time }, access: "owner-draft", records, coverage: Object.fromEntries(kinds.map(k => [k, records[k].length])) as Record<RecordKind, number> };
const statuses = ["running", "manual", "manual", "awaiting-review", "expired"] as const;
const jobs: QueueJob[] = statuses.map((status, n) => ({ id: id(70 + n), study_id: study, campaign_id: id(30 + n), execution_mode: n === 1 || n === 2 ? "manual" : "automatic", priority: n + 1, status, reason: ["Illustrative numerical execution", "Equipment and an intervention design are required", "Primary normative text needs substantive examination", "Recorded discrepancy needs claim-specific review", "Lease expired; outcome uncertain, no automatic retry"][n], readiness: status === "manual" ? "blocked" : status, blockers: status === "manual" ? ["Automatic execution is inapplicable; a domain operator is required."] : [], dependencies: n === 1 ? [{ job_id: id(70), requirement: "reviewed-evidence" }] : [], exclusive_resources: n === 0 ? ["machine:example-host"] : [], followup_of: null, run_id: n === 3 ? id(90) : null, run_status: n === 3 ? "complete" : null, created_at: time, updated_at: time, definition_sha256: "0".repeat(64), lease_until: status === "running" ? "2026-10-07T00:10:00Z" : null }));
export const QUEUE_EXAMPLE: ResearchQueue = { version: "research-queue-v1", study_id: study, access: "owner-private", workers_enabled: false, jobs, events: jobs.map((job, n) => ({ id: id(100 + n), study_id: study, job_id: job.id, event: "illustration", status: job.status, reason: job.reason, details: { data_origin: "software-fixture", measured_charges_usd: null }, created_at: time })), limits: { global_jobs: 4, study_jobs: 2, invocation_jobs: 2, lease_seconds: 600, automatic_retries: 0 }, coverage: { jobs: jobs.length, events: jobs.length }, limitations: "All rows, identities and timestamps in this example are synthetic illustrations. No experiment was executed and no independent review is asserted." };
