"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/app/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/app/components/ui/select";
import { Table } from "@/app/components/ui/table";
import { RELIABLE_STUDY_MODULE_PATH as PATH } from "@/lib/test-modules";
import { numberLabel, rangeLabel, type ReliableData } from "@/lib/reliable-study";
export function ReliableDashboard({ data }: { data: ReliableData }) {
  const [stage,setStage] = useState("main"), [skew,setSkew] = useState("0.3"), [budget,setBudget] = useState("131072");
  const configs = data.configurations.filter(c => c.campaign_id === `reliable-${stage}-v1` && c.skewness === Number(skew) && c.budget_bytes === Number(budget));
  const summaries = configs.map(c => ({ config: c, summary: data.summaries.find(s => s.configuration_id === c.id) }));
  const max = Math.max(1,...summaries.map(r => r.summary?.statistics.outliers?.max ?? 0).filter(v => Number.isFinite(v)));
  const options = (label: string, value: string, onChange: (value: string) => void, entries: [string,string][]) => <div className="space-y-1 text-sm"><label id={`reliable-${label}`} className="block">{label}</label><Select value={value} onValueChange={v => { if (v) onChange(v); }} items={entries.map(([value,label]) => ({ value,label }))}><SelectTrigger aria-labelledby={`reliable-${label}`}><SelectValue /></SelectTrigger><SelectContent>{entries.map(([v,l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>;
  return <div className="space-y-6">
    <div className="rounded-lg border border-amber-500/40 bg-amber-500/5 p-4 text-sm"><strong>Limited assessment.</strong> New CPU measurements on generated streams and independent finite controls. Original trace-based curves, rare-event guarantees and hardware performance remain unvalidated. Scientific discrepancies remain visible.</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["CPU runs",`${numberLabel(data.meta.counts.runs,0)} recorded / 1,080 planned`],["Inputs","3 fixed streams · 250,000 updates each"],["Replications","10 fixed hash seeds / configuration"],["Uncertainty","Median and seed range; no CI"]].map(([label,value]) => <div className="rounded-lg border p-4" key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</div>
    <p className="text-sm text-muted-foreground">These are empirical CPU executions with synthetic inputs. No live network traffic, simulation of a deployed network, archived author measurements or AI-generated numerical estimates are included. Each input hash and key identity is matched across algorithms. Timing queries repeat traffic keys; errors census distinct observed keys plus three absent probes.</p>
    <div className="flex flex-wrap items-end gap-4">{options("Campaign",stage,setStage,[["main","Main · nominal memory"],["followup","Follow-up · allocated counters"]])}{options("Skewness",skew,setSkew,[["0.3","0.3"],["1.2","1.2"],["3.0","3.0"]])}{options("Budget",budget,setBudget,[["8192","8 KiB"],["32768","32 KiB"],["131072","128 KiB"]])}<a href={`${PATH}/api/results`} className="text-sm underline underline-offset-4">Download evidence (JSON)</a><a href={`${PATH}/api/results?format=csv`} className="text-sm underline underline-offset-4">Run metrics (CSV)</a><a href={`${PATH}/reproduction.zip`} className="text-sm underline underline-offset-4">Protocols & reproduction code</a><a href={`${PATH}/raw-cpu-v1.zip`} className="text-sm underline underline-offset-4">Per-key raw CPU data</a></div>
    <section className="rounded-lg border p-4"><h2 className="font-medium">Outliers across matched configurations</h2><p className="my-2 text-xs text-muted-foreground">Absolute error &gt; 25 count units. Bars show the median; lines show the descriptive min–max across ten fixed hash seeds. This is not a confidence interval.</p>{configs.length===0 ? <p role="status">No recorded configuration matches these controls. Missing results remain missing.</p> : <div className="overflow-x-auto"><svg role="img" aria-label="Outlier median and descriptive seed range" viewBox="0 0 700 270" className="min-w-[600px] w-full"><title>{"Outliers in keys; median and descriptive min–max, not confidence intervals."}</title>{summaries.map(({ config,summary },i) => { const s=summary?.statistics.outliers; const valid=s && [s.median,s.min,s.max].every(v => typeof v === "number" && Number.isFinite(v) && v >= 0); return <g key={config.id}><text x="0" y={i*42+22} fill="currentColor" fontSize="13">{config.algorithm}</text>{valid ? <g className="text-primary"><rect x="100" y={i*42+8} width={s.median!/max*430} height="18" fill="currentColor" opacity="0.75"/><path d={`M ${100+s.min!/max*430} ${i*42+17} H ${100+s.max!/max*430}`} stroke="currentColor" strokeWidth="2"/><text x="550" y={i*42+22} fill="currentColor" fontSize="12">{rangeLabel(s)}</text></g> : <text x="100" y={i*42+22} fill="currentColor" fontSize="12">{s ? "Invalid or missing measurement" : "Missing measurement"}</text>}</g>; })}</svg></div>}</section>
    <section className="rounded-lg border p-4"><h2 className="font-medium">Accuracy, memory and coverage</h2><p className="my-2 text-xs text-muted-foreground">Values are median (minimum–maximum). KiB = 1,024 bytes. Allocated counter memory excludes allocator overhead, object metadata and RSS. Paper MB/KB definitions remain unspecified. Null interval metrics on CM/CU are missing bounds, not zero violations.</p><div className="overflow-x-auto"><Table className="w-full text-left text-xs"><thead><tr>{["Algorithm","Runs","Outliers","AAE · counts/key","ARE","Invalid intervals · keys","Lost updates","Nominal / allocated bytes","Details"].map(v => <th className="p-2" key={v}>{v}</th>)}</tr></thead><tbody>{summaries.map(({ config,summary:s }) => <tr className="border-t" key={config.id}><td className="p-2">{config.algorithm}</td><td className="p-2">{s ? `${s.recorded}/${s.planned}; failed ${s.failed}, excluded ${s.excluded}` : "missing"}</td><td className="p-2">{rangeLabel(s?.statistics.outliers)}</td><td className="p-2">{rangeLabel(s?.statistics.aae)}</td><td className="p-2">{rangeLabel(s?.statistics.are)}</td><td className="p-2">{rangeLabel(s?.statistics.interval_violations)}</td><td className="p-2">{rangeLabel(s?.statistics.lost_mass)}</td><td className="p-2">{numberLabel(s?.statistics.nominal_bytes?.median,0)} / {numberLabel(s?.statistics.allocated_counter_bytes?.median,0)}</td><td className="p-2"><Button size="sm" variant="outline" nativeButton={false} render={<Link href={`${PATH}/chat?configuration=${encodeURIComponent(config.id)}`} />}>Prepare question</Button></td></tr>)}</tbody></Table></div><p className="mt-3 text-xs text-muted-foreground">Observed distinct keys: {numberLabel(summaries[0]?.summary?.observed_keys,0)}. All observed keys and three absent probes are queried. RS has no auxiliary fallback in these experiments; dropped mass invalidates its error guarantee. The formal theorem and hardware adaptations have different assumptions.</p></section>
    <section className="rounded-lg border p-4"><h2 className="font-medium">Local throughput</h2><p className="my-2 text-xs text-muted-foreground">Million updates/s and million repeated queries/s on one macOS arm64 workstation, compiled with O2. Single pass per fixed seed; descriptive timing variation. Different conditions from the paper’s Intel server.</p><div className="overflow-x-auto"><Table className="w-full text-left text-sm"><thead><tr><th className="p-2">Algorithm</th><th className="p-2">Insertion</th><th className="p-2">Query</th></tr></thead><tbody>{summaries.map(({ config,summary:s }) => <tr className="border-t" key={config.id}><td className="p-2">{config.algorithm}</td><td className="p-2">{rangeLabel(s?.statistics.insert_mups)}</td><td className="p-2">{rangeLabel(s?.statistics.query_mqps)}</td></tr>)}</tbody></Table></div></section>
    <section className="rounded-lg border p-4"><h2 className="font-medium">Published values · separate evidence</h2><p className="my-2 text-xs text-muted-foreground">Transcribed numbers with paper locations; these have not been replaced by our measurements. Curves were visually examined, without exhaustive digitization.</p>{data.published.map(p => <details className="mt-3 text-sm" key={p.id}><summary className="cursor-pointer">{p.metric} · {p.location}</summary><p className="mt-2 text-xs text-muted-foreground">{p.units}</p><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(p.values,null,2)}</pre></details>)}</section>
    <section className="space-y-3 rounded-lg border p-4"><h2 className="font-medium">Claims relevant to these results</h2>{data.claims.filter(c => ["memory","weighted-code","sensing","accuracy","speed","theory"].includes(c.id)).map(c => <div className="border-t pt-3 text-sm" key={c.id}><p className="font-medium">{c.description} · {c.assessment}</p><p className="mt-1">{c.evidence}</p><p className="mt-1 text-xs text-muted-foreground">{c.location}. {c.limitation}</p></div>)}<Link href={`${PATH}/methods`} className="inline-block text-sm underline underline-offset-4">All claim coverage, controls and protocols</Link></section>
  </div>;
}
