import { Http2Header } from "@/app/components/http2-study/header";
import { getHttp2Data } from "@/lib/http2-study-server";
export const dynamic = "force-dynamic";
export default async function Literature() {
  const data = await getHttp2Data();
  return <main className="mx-auto max-w-6xl space-y-4 px-4 py-6"><Http2Header title="Literature and retrieval coverage" description="The main paper and all 48 directly cited sources. Bibliographies of those sources are not recursively expanded. Downloaded, complete review, partial review, unreviewed and unavailable remain distinct." />
    {data ? <><div className="rounded-lg border p-4 text-sm">{["complete", "partial", "unreviewed", "unavailable"].map(status => <span className="mr-5 inline-block" key={status}>{status}: {data.sources.filter(s => s.review_status === status).length}</span>)}<p className="mt-2 text-muted-foreground">Partial notes state the sections actually reviewed. Unavailable entries carry no full-text findings. Hashes identify retrieved bytes, not the publication’s identity by themselves. Current web pages may differ from the cited-date version.</p></div>{data.sources.map(s => <article key={s.reference_number} className="space-y-2 rounded-lg border p-4 text-sm"><p className="text-xs text-muted-foreground">{s.reference_number === 0 ? "Main paper" : `[${s.reference_number}]`} · {s.kind} · download: {s.download_status} · review: <strong>{s.review_status}</strong></p><h2 className="font-medium">{s.citation}</h2><div className="flex flex-wrap gap-4">{s.source_url && <a href={s.source_url} className="underline underline-offset-4" target="_blank" rel="noreferrer">Cited source</a>}{s.retrieved_url?.startsWith("https://") && <a href={s.retrieved_url} className="underline underline-offset-4" target="_blank" rel="noreferrer">Retrieved version</a>}{s.doi && <a href={`https://doi.org/${s.doi}`} className="underline underline-offset-4" target="_blank" rel="noreferrer">DOI</a>}</div><p className="text-xs text-muted-foreground">{s.retrieved_version ?? "No full text retrieved"} · pages {s.pages ?? "unavailable"}</p><p>{s.findings ?? "No reviewed findings."}</p><p className="text-muted-foreground">{s.limitations}</p><p className="break-all font-mono text-xs">SHA-256: {s.sha256 ?? "unavailable"}</p><details><summary className="cursor-pointer text-xs">Retrieval audit</summary><pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(s.retrieval_audit, null, 2)}</pre></details></article>)}</> : <p>Source records are unavailable.</p>}
  </main>;
}
