import { ReliableHeader } from "@/app/components/reliable-study/header";
import { getReliableData } from "@/lib/reliable-study-server";
import { RELIABLE_STUDY_MODULE_PATH as PATH } from "@/lib/test-modules";
export const dynamic = "force-dynamic";
export default async function Methods() {
 const data=await getReliableData();
 return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6"><ReliableHeader title="Methods, controls and claim coverage" description="Four frozen protocols preserve exploratory controls, the main nominal-memory campaign, independent correctness checks and the predeclared allocated-memory follow-up." />{data ? <>
 <section className="space-y-3 rounded-lg border p-4 text-sm"><h2 className="font-medium">Conditions and limits</h2><p>Author revision 5a83f03c775142401d23a78e7e81b163ddf7b604 (January 2024). Its original C++ unit-update algorithms remain byte-exact. A separate adapter controls inputs and the RNG; a separately versioned correction handles weighted filter updates. Exact input bytes, configurations, original stdout and transformation hashes are preserved. Every planned main/follow-up run is recorded.</p><p>The fixed panel is three 250,000-item streams on keys 1–4,096, with skewness 0.3, 1.2 and 3.0; six algorithms, three budgets and ten seeds per configuration. Errors use exact distinct-key truth; ARE excludes zero-truth absent probes. Whole runs are the replication unit. Queries and keys share collision state; fixed seeds and one host do not support an inferential CI or rare-event failure estimate.</p><p>Original trace identifiers, preprocessing bytes, seed draws and result vectors are unavailable. No archived author-data reanalysis was possible. Our generated-stream CPU executions are new empirical measurements using author implementations. Independent small-state arithmetic shares no sketch code; CSV validation shares inputs and emitted estimates. Neither establishes broader causality, effectiveness or generalization.</p><p>FPGA/Tofino equipment and licensed tools are unavailable. Original network deployment and line-rate claims remain untested. Orbital epochs, terminal populations and propagation-delay experiments are inapplicable to this paper’s domain. Full Appendix A proof verification and all plotted numerical cells remain incomplete.</p><a className="underline underline-offset-4" href={`${PATH}/reproduction.zip`}>Download protocols, locks, reproduction commands and validation</a></section>
 <section className="space-y-3 rounded-lg border p-4 text-sm"><h2 className="font-medium">Assessment labels</h2>{Object.entries(data.meta.label_definitions).map(([key,value]) => <p key={key}><strong>{key}:</strong> {value}</p>)}</section>
 <section className="space-y-3 rounded-lg border p-4 text-sm"><h2 className="font-medium">Correctness controls</h2>{data.controls.map(c => <details key={c.id}><summary className="cursor-pointer">{c.id} · {c.stage}</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(c.payload,null,2)}</pre></details>)}</section>
 <section className="space-y-4 rounded-lg border p-4"><h2 className="font-medium">Claim-by-claim evidence</h2>{data.claims.map(c => <article className="border-t pt-3 text-sm" key={c.id}><h3 className="font-medium">{c.description} · {c.assessment}</h3><p className="mt-1 text-xs text-muted-foreground">{c.location}</p><p className="mt-2">{c.evidence}</p><p className="mt-1 text-muted-foreground">{c.limitation}</p><details className="mt-2"><summary className="cursor-pointer">Check, inputs and feasibility</summary><p>{c.proposed_check}; inputs: {c.required_inputs}. {c.feasibility}.</p></details></article>)}</section>
 <section className="space-y-3 rounded-lg border p-4"><h2 className="font-medium">Frozen protocols</h2>{data.protocols.map(p => <details className="text-sm" key={p.id}><summary className="cursor-pointer">{p.id} · {p.stage}</summary><p className="mt-2 break-all text-xs">Locked {p.locked_at}; SHA-256 {p.sha256}</p><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(p.document,null,2)}</pre></details>)}</section>
 <section className="space-y-3 rounded-lg border p-4 text-sm"><h2 className="font-medium">Usage and release verification</h2><p>Recorded durations and original-byte sizes are measured. No AWS experiment instances were created. Workstation allocation, orchestration costs, reconciled storage charges and unavailable model usage remain missing. Model list-price estimates are separate from measured billing.</p><pre className="max-h-60 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(data.meta.costs,null,2)}</pre><p>Scientific coverage and software release checks are separate. Authentication requires a legitimate Google session; no synthetic identity substitutes for an actual signed-in request. Chat evaluation cases are development regressions unless explicitly identified as held out; AI answer inspection is not human review.</p><a className="underline underline-offset-4" href={`${PATH}/chat-release.json`}>Published prompt and evaluated answers</a><p><a className="underline underline-offset-4" href={`${PATH}/api/release`}>Software verification and conditional gaps</a> · <a className="underline underline-offset-4" href={`${PATH}/download-manifest.json`}>Download hashes</a></p></section>
 </> : <p>Study evidence is unavailable. No results inferred.</p>}</main>;
}
