"use client";
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "@/app/components/ui/table";
import { useState } from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/app/components/ui/select";
import { numberLabel as num } from "@/lib/reliable-study";
import { IPV6_METRICS, IPV6_MTUS, IPV6_MTU_LABELS, type IPv6Data } from "@/lib/ipv6-study";
import { IPV6_STUDY_MODULE_PATH as PATH } from "@/lib/test-modules";
function Choice({ id, label, value, options, change }: { id: string; label: string; value: string; options: { value: string; label: string }[]; change: (v: string) => void }) {
 return <div className="space-y-1"><label className="text-xs font-medium" htmlFor={id}>{label}</label><Select items={options} value={value} onValueChange={v => { if (v !== null) change(v); }}><SelectTrigger id={id} className="w-full"><SelectValue /></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
const choices = (values: string[]) => values.map(value => ({ value, label: value.replaceAll("_", " ") }));
export function IPv6Dashboard({ data }: { data: IPv6Data }) {
 const [epoch, setEpoch] = useState("current"), [cohort, setCohort] = useState("dnssec"), [upstream, setUpstream] = useState("no-lgi"), [edns, setEdns] = useState("4096"), [metric, setMetric] = useState("TIMEOUT");
 const rows = IPV6_MTUS.flatMap(mtu => ["v4-only", "v6-only", "ds"].map(family => {
  const c = data.configurations.find(c => c.mtu === mtu && c.family === family && c.cohort === cohort && c.upstream === upstream && String(c.edns_bytes) === edns);
  const s = c && data.summaries.find(s => s.configuration_id === c.id && s.epoch === epoch)?.statistics[metric];
  const p = c && data.comparisons.find(p => p.configuration_id === c.id && p.epoch === epoch && p.metric === metric);
  return { c, s, p, mtu, family };
 }));
 const recorded = rows.filter(r => r.s?.mean !== null && r.s?.mean !== undefined && Number.isFinite(r.s.mean));
 const max = Math.max(0.001, ...recorded.map(r => r.s!.mean!)) * 1.12;
 return <div className="space-y-6"><Card><CardHeader><CardTitle>Numerical agreement with a limited historical scope</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><strong>{data.meta.validation.reproduced_cells.toLocaleString()} / {data.meta.validation.published_cells.toLocaleString()} absolute cells reproduced</strong> in Figures 13–15 within 0.0051 percentage points. The original folding function agrees with independently written arithmetic on the same recorded summaries.</p><p>Archived DNS observations from April–September 2025; no new network measurements or simulations. Two archive days are unavailable. Most direct sources have not received complete review. The historical summary agreement does not establish universal IPv6 readiness, packet delivery, causality or standards compliance.</p><p className="text-muted-foreground">Daily aggregates repeatedly observe overlapping NS sets, servers and paths from one AS. Coverage counts are not independent replications. Min–max ranges are descriptive; this design does not support an inferential confidence interval.</p></CardContent></Card>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Choice id="ipv6-epoch" label="Historical epoch" value={epoch} change={setEpoch} options={[{ value: "current", label: "Jun 25–Sep 14 · current" }, { value: "pre-lgi", label: "May 25–Jun 14 · pre-LGI" }, { value: "tcp-error", label: "Apr 10–May 23 · TCP limit" }]} /><Choice id="ipv6-cohort" label="DNSSEC cohort" value={cohort} change={setCohort} options={choices(["dnssec", "no-dnssec"])} /><Choice id="ipv6-upstream" label="Recorded upstream" value={upstream} change={setUpstream} options={choices(["no-lgi", "lgi"])} /><Choice id="ipv6-edns" label="EDNS payload (bytes)" value={edns} change={setEdns} options={choices(["512", "1232", "4096"])} /><Choice id="ipv6-metric" label="Metric" value={metric} change={setMetric} options={choices(IPV6_METRICS)} /></div>
 <Card><CardHeader><CardTitle>{metric.replaceAll("_", " ")} · recorded daily mean (%)</CardTitle></CardHeader><CardContent className="space-y-3">{recorded.length ? <svg role="img" aria-label={`${metric} by MTU and address family`} viewBox="0 0 680 310" className="w-full"><title>{`${metric}: descriptive daily means, ${epoch}, ${cohort}, ${upstream}, EDNS ${edns} bytes; no confidence intervals`}</title>{[0, 0.25, 0.5, 0.75, 1].map(t => <g key={t}><line x1="62" x2="665" y1={240 - 195 * t} y2={240 - 195 * t} stroke="var(--border)" /><text x="54" y={244 - 195 * t} textAnchor="end" fill="var(--muted-foreground)" fontSize="11">{num(max * t, 2)}%</text></g>)}{IPV6_MTUS.map((mtu, i) => <g key={mtu}>{["v4-only", "v6-only", "ds"].map((family, j) => { const r = rows.find(r => r.mtu === mtu && r.family === family); const v = r?.s?.mean; return v !== null && v !== undefined && Number.isFinite(v) ? <rect key={family} x={83 + i * 148 + j * 31} y={240 - v / max * 195} width="25" height={v / max * 195} fill={`var(--chart-${j + 1})`}><title>{`${IPV6_MTU_LABELS[mtu]}, ${family}: ${num(v, 4)}%, ${r?.s?.n ?? "missing"}/${r?.s?.planned ?? "missing"} days`}</title></rect> : null; })}<text x={124 + i * 148} y="260" textAnchor="middle" fill="var(--foreground)" fontSize="11">{i === 0 ? "1500" : i === 1 ? "1280 + PMTUD" : i === 2 ? "1280 link" : "1280 path"}</text></g>)}{["IPv4 only", "IPv6 only", "Dual stack"].map((f, i) => <g key={f}><rect x={120 + i * 170} y="283" width="12" height="12" fill={`var(--chart-${i + 1})`} /><text x={140 + i * 170} y="294" fill="var(--foreground)" fontSize="12">{f}</text></g>)}</svg> : <p role="status">No valid observations for this configuration. Missing or invalid values are not zero.</p>}<p className="text-xs text-muted-foreground">TIMEOUT and SERVFAIL use NS-set outcomes. Packet metrics use observed UDP server identities. TCP fallback is TCP/UDP × 100, a ratio that can exceed 100%; these denominators cannot be interchanged.</p></CardContent></Card>
 <div className="overflow-x-auto rounded-lg border"><Table className="w-full min-w-[1000px] text-left text-xs"><TableCaption className="p-3 text-left text-sm font-medium">Equivalent configurations · published values kept separate</TableCaption><TableHeader className="bg-muted"><TableRow>{["MTU / family", "Mean %", "Paper %", "Difference (pp)", "Daily min–max %", "Valid / planned", "Missing / invalid", "Pooled %", "Routing sensitivity %", "Matched IPv6−IPv4 (pp)"].map(h => <TableHead key={h} className="p-3">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r => <TableRow key={`${r.mtu}-${r.family}`} className="border-t"><TableCell className="p-3">{r.c ? <Link className="text-primary underline" href={`${PATH}/chat?configuration=${encodeURIComponent(r.c.id)}`}>{IPV6_MTU_LABELS[r.mtu]}<br />{r.family}</Link> : `${IPV6_MTU_LABELS[r.mtu]} · ${r.family}`}</TableCell><TableCell className="p-3">{num(r.s?.mean, 4)}</TableCell><TableCell className="p-3">{r.p ? num(Number(r.p.published), 2) : "not compared"}</TableCell><TableCell className="p-3">{r.p ? num(Number(r.p.difference_pp), 5) : "not compared"}</TableCell><TableCell className="p-3">{r.s ? `${num(r.s.min, 4)}–${num(r.s.max, 4)}` : "missing"}</TableCell><TableCell className="p-3">{r.s ? `${r.s.n} / ${r.s.planned}` : "missing"}</TableCell><TableCell className="p-3">{r.s ? `${r.s.missing} / ${r.s.invalid}` : "missing"}</TableCell><TableCell className="p-3">{num(r.s?.pooled, 4)}</TableCell><TableCell className="p-3">{num(r.s?.routing_sensitivity_mean, 4)}<br />n={r.s?.routing_sensitivity_n ?? "missing"}</TableCell><TableCell className="p-3">{r.family === "v6-only" ? `${num(r.s?.paired_v6_minus_v4_mean_pp, 4)}; n=${r.s?.paired_days ?? "missing"}` : "inapplicable"}</TableCell></TableRow>)}</TableBody></Table></div>
 <Card><CardHeader><CardTitle>Coverage and discrepancies</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>The paper’s RQ3 summary reverses the direction of its Section 4.4 fragmentation percentages. RFC 3901 recommends at least one IPv4-reachable authoritative server; the paper says two. Finite controls demonstrate released aggregation defects, but their occurrence in the published campaign is unestablished.</p><p>DNSSEC cohorts follow the authors’ observed-signature classification. This is an association, not randomized assignment. Before/after LGI comparisons also change calendar time and cannot isolate the policy’s causal effect.</p><Link className="text-primary underline" href={`${PATH}/methods`}>Read all claim assessments, exclusions and controls</Link></CardContent></Card>
 <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Archive failures and excluded days</summary><ul className="mt-3 space-y-2 text-xs">{data.runs.filter(r => r.status !== "complete").map(r => <li key={r.id}><strong>{r.id} · {r.status}</strong>: {r.reason}</li>)}</ul><p className="mt-3 text-xs">July 31: one no-DNSSEC / 1500 / no-LGI / IPv4 / EDNS 4096 packet aggregate is absent. Its packet coverage is 80/82 calendar days (80/81 available archive days); DNS outcome coverage remains 81/82. The missing packet observation was not replaced by zero.</p></details></div>;
}
